# Deploys cloudnative-pg operator & postgresql cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-secrets-operator
  namespace: flux-system
  labels:
    environment: latest
spec:
  dependsOn:
    - name: flux-system

  interval: 24h
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/vault-secrets-operator/operator

  # healthChecks:
  #   - apiVersion: postgresql.cnpg.io/v1
  #     kind: Cluster
  #     name: pg-core
  #     namespace: postgres
