---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: web-artifacts
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: web-infrastructure
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/"
          to: "@artifact/"
    # - name: apps
    #   originRevision: "@monorepo"
    #   copy:
    #     - from: "@monorepo/apps/base/**"
    #       to: "@artifact/base/"
    #     - from: "@monorepo/apps/staging/**"
    #       to: "@artifact/staging/"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s

  sourceRef:
    kind: ExternalArtifact
    name: web-infrastructure
  path: "./clusters/cluster04/web"
  prune: true
