# Deploys cloudnative-pg operator & postgresql cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vso
  namespace: flux-system
  labels:
    environment: latest
spec:

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/vault-secrets-operator/operator
  